// content.js
const content = {
    option1: {
      link: '/read/1',
      imageUrl: '/images/voiceofp.jpg',
      title: 'sustainable devlopment and practices',
      description: 'Description for Renewable Energy',
      listItems: ['SOLAR ENERGY', 'THERMAL ENERGY', 'WIND ENERGY'],
    },
    option2: {
      link: '/read/1',
      imageUrl: '/images/voiceofp.jpg',
      title: 'Audio Book',
      description: 'Description for Audio Book',
      listItems: ['Item 1', 'Item 2', 'Item 3'],
    },
    option3: {
      link: '/read/1',
      imageUrl: '/images/voiceofp.jpg',
      title: 'Articles & Stories',
      description: 'Description for Articles & Stories',
      listItems: ['Item 1', 'Item 2', 'Item 3'],
    },
    option4: {
      link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 2', 'Item 2', 'Item 3'],
      },
      option5: {
        link: '/read/1',

        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 2', 'Item 2', 'Item 3'],
      },
      option6: {      
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 2', 'Item 2', 'Item 3'],
      },
      option7: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option8: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option9: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option10: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option11: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option12: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option13: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option14: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option15: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option16: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option17: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option18: {
        link: '/read/1',
        imageUrl: '/images/articles.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      option19: {
        link: '/read/1',
        imageUrl: '/images/voiceofp.jpg',
        title: 'Articles & Stories',
        description: 'Description for Articles & Stories',
        listItems: ['Item 9', 'Item 2', 'Item 3'],
      },
      
  };
  
  export default content;
  